### ISSUE TITLE
obvious misalignments

### ISSUE THREAD

**Issue by pwkooij** [smirarab/pasta#20]
Hi,

I've been using PASTA for a while now and in general very happy with the quality. However, I have some issues with a dataset I currently work on (1597 individuals, fungal, ITS for most, LSU for over half, concatenated). I always check my final alignment for errors, and I always notice several sequences clearly misaligned. I manually improved my dataset, reducing the number of characters from around 6000 to around 2500, mainly due to misalignments. 

Any idea what could help improve the results? Should I try and run it with a different aligner? Or would a different merger improve it? Or both? And if so, which tools do you suggest I use?

Cheers
Pepijn

**Comment by smirarab** [comment]
Dear Pepijn, 

I know there has been a long time since I noticed this. However, since version 1.8.0 PASTA has improved in terms of accuracy a bit. Can you try the latest version perhaps?

Thanks
