### ISSUE TITLE
Docker image instead of VM

### ISSUE THREAD

**Issue by niemasd** [smirarab/pasta#32]
It would be useful if PASTA had a Docker image instead of a VM. It would make it easier to deploy on cloud compute engines. I'm working on this in my own forked PASTA repository (https://github.com/niemasd/pasta), and once the Dockerfile is done and I guarantee that the Docker image generates properly, I'll merge to this repo and set up an automated DockerHub repository (i.e., it'll generate an updated Docker image automatically each time a push is made to this repository)

**Comment by niemasd** [comment]
Merged: https://github.com/smirarab/pasta/commit/4ebf1d646b32c81f996db24fc3eee0674c526574

Need to create DockerHub repository that will automatically build images from this repository

**Comment by smirarab** [comment]
Is this finished? Thanks!

**Comment by niemasd** [comment]
According to the [PASTA DockerHub repository](https://hub.docker.com/r/smirarab/pasta/builds), it seems as though the most recent build was 4 months ago, which seems to also be the [most recent commit](https://github.com/smirarab/pasta/commits/master). Also, the DockerHub repo says "Autobuilds". Thus, I am fairly certain it is finished and working properly (but it would of course be good to always check each time a future push is made to the master branch)
