### ISSUE TITLE
--num_cpus didn't work for me

### ISSUE THREAD

**Issue by mcsimenc** [smirarab/pasta#35]
Hey, I'm looking forward to seeing if pasta will work for my application. I was trying out some options and found that this one didn't work:
`pasta --num_cpus=1 -i elements.fasta`
```
Usage: pasta [options] <settings_file1> <settings_file2> ...

pasta: error: no such option: --num_cpus
```

Not necessary for me that it works but I thought you should know.

**Comment by smirarab** [comment]
Was this solved (sorry this went unnoticed). 

```bash
run_pasta.py --num-cpus 1 -i data/small.fasta
```
Works perfectly fine on my machine. Can you try again? Did you type or copy paste `--num-cpus 1`? Perhaps you copy-pasted and something funny happened with characters?

**Comment by mcsimenc** [comment]
It's alright, actually, I see you placed a dash between num and cpus while I placed an underscore. I am not sure if I will revisit what I was working on there, but thank you Siavash for responding. Cheers.
