### ISSUE TITLE
Terminated abnormally 

### ISSUE THREAD

**Issue by lalalagartija** [smirarab/pasta#55]
Hi, 

PASTA did run the analysis on me sequences but I don't know if it terminated correctly. 
Her is my log : 

> PASTA INFO: Directory for temporary files created at /home/ME/.pasta/pastajob/tempuso6govw
> PASTA INFO: Name translation information saved to /home/ME/Work/Metagenomics/Ref_vs_us/W_domains_over150_tree/pastajob_temp_name_translation.txt as safe name, original name, blank line format.
> PASTA INFO: Creating a starting tree for the PASTA algorithm...
> PASTA INFO: Performing initial alignment of the entire data matrix...
> PASTA INFO: Performing initial tree search to get starting tree...
> PASTA INFO: Starting PASTA algorithm on initial tree...
> PASTA INFO: Max subproblem set to 200
> PASTA INFO: Step 0. Realigning with decomposition strategy set to mincluster
> PASTA INFO: Step 0. Alignment obtained. Tree inference beginning...
> PASTA INFO: realignment accepted and score improved.
> PASTA INFO: current score: -1686981.867, best score: -1686981.867
> PASTA INFO: TreeShrink option has been turned off!
> PASTA INFO: Step 1. Realigning with decomposition strategy set to mincluster
> PASTA INFO: Step 1. Alignment obtained. Tree inference beginning...
> PASTA INFO: realignment accepted and score improved.
> PASTA INFO: current score: -1284552.171, best score: -1284552.171
> PASTA INFO: TreeShrink option has been turned off!
> PASTA INFO: Step 2. Realigning with decomposition strategy set to mincluster
> PASTA INFO: Step 2. Alignment obtained. Tree inference beginning...
> PASTA INFO: realignment accepted and score improved.
> PASTA INFO: current score: -1283118.396, best score: -1283118.396
> PASTA INFO: TreeShrink option has been turned off!
> PASTA INFO: Writing resulting alignment to /home/ME/Work/Metagenomics/Ref_vs_us/W_domains_over150_tree/pastajob.marker001.permagenomics150_noAnoJ.faa.aln
> PASTA INFO: Writing resulting tree to /home/ME/Work/Metagenomics/Ref_vs_us/W_domains_over150_tree/pastajob.tre
> PASTA INFO: Writing resulting likelihood score to /home/ME/Work/Metagenomics/Ref_vs_us/W_domains_over150_tree/pastajob.score.txt
> PASTA INFO: The resulting alignment (with the names in a "safe" form) was first written as the file "/home/ME/Work/Metagenomics/Ref_vs_us/W_domains_over150_tree/pastajob_temp_iteration_2_seq_alignment.txt"
> PASTA INFO: The resulting tree (with the names in a "safe" form) was first written as the file "/home/ME/Work/Metagenomics/Ref_vs_us/W_domains_over150_tree/pastajob_temp_iteration_2_tree.tre"
> PASTA INFO: Total time spent: 7595.885284662247s

All the temporary files are still present : "pastajob_temp_iteration_0_..." up to 2 iterations.
Is this how it is supposed to end ? 

Thank you very much

**Comment by RobBarringer** [comment]
Hi @lalalagartija 

This seems pretty normal. It has performed the initial alignment, and then 2 more steps ('Step 1' and 'Step 2'). Did you use the default amount of repeats? If so, this the default is 3 itertaions (I think - the initial and 2 further iterations), which fits this output.

The final line saying 'PASTA INFO: Total time spent' prints at the end of all of my runs, so it's finished normally I think. I can't see any error messages either so it looks like it successfully executed and finished. There should be an error file output that you can look at to see if any errors were encountered I think. If that doesn't say anything, then it should be fine.

Cheers,

Rob

**Comment by lalalagartija** [comment]
Thank you very much ! Then it is fine, it just didn't manage to remove the temporary files. The error file is empy and this was my command : 
`python ~/Software/PASTA/pasta/run_pasta.py -i permagenomics150_noAnoJ.faa --datatype Protein`
