### ISSUE TITLE
ValueError: The alignment file has no sequences. PASTA quits.

### ISSUE THREAD

**Issue by srautonu** [smirarab/pasta#58]
**Command line used:**
python3 run_pasta.py --max-mem-mb=32768 -o results -i corona.cleaned.true.fasta -j corona

The input file has been attached herewith. The file contains whole genome sequences. Each sequence is > 31000 bp. Would that be a problem?

**Console output**
PASTA INFO: Directory for temporary files created at /home/mrahman/.pasta/corona/temps4ygugvk
PASTA INFO: Name translation information saved to /home/mrahman/BioTools/pasta/results/corona_temp_name_translation.txt as safe name, original name, blank line format.
PASTA INFO: Creating a starting tree for the PASTA algorithm...
PASTA INFO: Performing initial alignment of the entire data matrix...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/mrahman/BioTools/pasta/pasta/scheduler.py", line 197, in __call__
    job.results = job.result_processor()
  File "/home/mrahman/BioTools/pasta/pasta/tools.py", line 283, in <lambda>
    temp_fs=self.temp_fs)
  File "/home/mrahman/BioTools/pasta/pasta/tools.py", line 79, in read_internal_alignment
    raise ValueError("The alignment file %s has no sequences. PASTA quits." % fn)
ValueError: The alignment file /home/mrahman/.pasta/corona/temps4ygugvk/init_aln/tempmafftd1kvty9_/input.aligned has no sequences. PASTA quits.

[corona.cleaned.true.fasta.txt](https://github.com/smirarab/pasta/files/6501234/corona.cleaned.true.fasta.txt)

**Comment by smirarab** [comment]
Yes, my guess is that the sequences are too long for it to work out of box, and some changes are needed.

**Comment by xinyu-g** [comment]
Hi  @srautonu, I know this was quite a while ago, but were you able to resolve this problem?

**Comment by srautonu** [comment]
@xinyu-g I do not think so.
