### ISSUE TITLE
create release

### ISSUE THREAD

**Issue by sjanssen2** [smirarab/pasta#65]
Hi @smirarab ,
I was looking into bioconda SEPP issues https://github.com/bioconda/bioconda-recipes/pull/44523 and found that it requires pasta for python 3.8.
I am trying to update the according bioconda recipe https://github.com/bioconda/bioconda-recipes/pull/44543 but CI/CD is complaining about a missing release tag of your software. Could you therefore create a release here via the github web site for your current version 1.9.0 ?
Thanks,
Stefan

**Comment by smirarab** [comment]
Just did. Thanks.
